[package]
name = "iban-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
thiserror = "1.0.56"

[build-dependencies]
anyhow = "1.0.79"
csv = "1.3.0"
regex = "1.10.2"
quote = "1.0.35"